name: 'Install Inochi2D SDK'
inputs:
  tag:
    required: false
    description: 'Tag of SDK to fetch.'
    type: string
    default: 'latest'
  sdk:
    required: true
    description: 'Specific SDK to fetch.'
    type: string
runs:
  using: "composite"
  steps:
    - name: 'Install ${{ inputs.sdk }} toolchain...'
      shell: bash
      run: |
        echo "Installing SDK to $RUNNER_TOOL_CACHE..."

        wget -q https://github.com/Inochi2D/sdk-toolchain/releases/download/${{ inputs.tag }}/${{ inputs.sdk }}.tar.gz
        tar -xf ${{ inputs.sdk }}.tar.gz -C "$RUNNER_TOOL_CACHE" &> /dev/null
        if [ -f "$RUNNER_TOOL_CACHE/ci_postinstall.sh" ]; then
          chmod +x "$RUNNER_TOOL_CACHE/ci_postinstall.sh"
          source "$RUNNER_TOOL_CACHE/ci_postinstall.sh"
        fi