name: 'Install Inochi2D SDK'
inputs:
  tag:
    required: false
    description: 'Tag of SDK to fetch.'
    type: string
    default: 'latest'
  sdk:
    required: true
    description: 'Specific SDK to fetch.'
    type: string
runs:
  using: "composite"
  steps:
    - name: 'Install ${{ inputs.sdk }} toolchain...'
      shell: bash
      run: |
        wget https://github.com/Inochi2D/sdk-toolchain/releases/download/${{ inputs.tag }}/${{ inputs.sdk }}.tar.gz
        tar -xf ${{ inputs.sdk }}.tar.gz -C ${{ runner.tool_cache }} &> /dev/null
        if [ -f '$RUNNER_TOOL_CACHE/ci_postinstall.sh' ]; then
          source $RUNNER_TOOL_CACHE/ci_postinstall.sh
        fi 

    - name: 'Add ${{ inputs.sdk }} to PATH...'
      shell: bash
      run: |
        echo "${{ runner.tool_cache }}/ldc2/bin:${{ runner.tool_cache }}/ldc2/lib" >> $GITHUB_PATH
